"use strict";
const assert = require("assert"); const fs = require("fs"); const os = require("os"); const path = require("path"); const { spawnSync } = require("child_process"); const test = require("node:test"); const { dispatch } = require("../../src/cli/main.cjs"); const { validate } = require("../../src/protocol/schema.cjs");
const scenario = path.resolve(__dirname, "../../examples/basic-three/scenario.json"), projectRoot = path.dirname(scenario);
function runtime(root) { const file = path.join(root, "runtime.json"); fs.writeFileSync(file, `${JSON.stringify({ schema_version: 1, trust_profile: "reviewed-local@1", project_root: projectRoot, origin: "http://127.0.0.1:41733", host_profile: "current-mac-arm64@1", attempts: 1 })}\n`); return file; }
function captureSet(runRoot) { const attempt = path.join(runRoot, "attempt-1"), manifest = JSON.parse(fs.readFileSync(path.join(attempt, "capture-set.json"))); return { attempt, manifest, captures: manifest.captures.map((item) => validate("capture.schema.json", JSON.parse(fs.readFileSync(path.join(attempt, item.capture_path))))) }; }
test("real served full matrix and replay converge across two fresh runs with same-render closure", async (t) => { const raw = fs.mkdtempSync(path.join(os.tmpdir(), "atlas-3d-real-")), root = fs.realpathSync(raw); t.after(() => fs.rmSync(raw, { recursive: true, force: true })); const config = runtime(root), runs = path.join(root, "runs"); fs.mkdirSync(runs); const one = dispatch(["run", "--scenario", scenario, "--runtime-config", config, "--artifact-root", runs, "--run-id", "fresh-a-1"]); const two = dispatch(["run", "--scenario", scenario, "--runtime-config", config, "--artifact-root", runs, "--run-id", "fresh-a-2"]); assert.strictEqual(one.status, "passed"); assert.strictEqual(two.status, "passed"); const check = dispatch(["check-run", "--run-root", one.run_root]); assert.strictEqual(check.status, "passed"); assert.strictEqual(check.capture_count, 12); const a = captureSet(one.run_root), b = captureSet(two.run_root); assert.strictEqual(a.manifest.capture_count, 12); assert.strictEqual(a.manifest.replay.converged, true); assert.strictEqual(a.manifest.replay.fresh_a_digest, a.manifest.replay.same_context_a_digest); assert.strictEqual(a.manifest.replay.fresh_a_digest, a.manifest.replay.second_fresh_a_digest); assert.deepStrictEqual(a.manifest.captures.map((item) => item.png_sha256), b.manifest.captures.map((item) => item.png_sha256)); assert.deepStrictEqual(a.captures.map((item) => item.canonical), b.captures.map((item) => item.canonical)); for (const capture of a.captures) { assert.deepStrictEqual(capture.transport.pre, capture.transport.post); assert(capture.transport.actual_launch_argv.includes("--user-data-dir=<ephemeral-profile>")); assert(/^[a-f0-9]{64}$/.test(capture.transport.actual_launch_argv_digest)); assert.strictEqual(capture.transport.process_audit.real_user_library_refs, 0); assert(capture.transport.process_audit.owned_runtime_refs > 0); assert.strictEqual(Object.hasOwn(capture, "captureToken"), false); } assert.strictEqual(fs.existsSync(path.join(a.attempt, ".browser-runtime")), false); assert.throws(() => validate("capture.schema.json", { ...a.captures[0], captureToken: "must-not-persist" }), /additional properties/i); const file = path.join(a.attempt, a.manifest.captures[0].capture_path); fs.appendFileSync(file, " "); assert.throws(() => dispatch(["check-run", "--run-root", one.run_root]), /digest|closure|evidence/i); });

test("real industrial run persists profile-complete canonical state and passes native-then-domain check-run", (t) => {
  const raw = fs.mkdtempSync(path.join(os.tmpdir(), "atlas-3d-industrial-real-")), root = fs.realpathSync(raw);
  t.after(() => fs.rmSync(raw, { recursive: true, force: true }));
  const config = runtime(root), runs = path.join(root, "runs"), industrialScenario = path.resolve(__dirname, "../../examples/basic-three/industrial-scenario.json");
  fs.mkdirSync(runs);
  const run = dispatch(["run", "--scenario", industrialScenario, "--runtime-config", config, "--artifact-root", runs, "--run-id", "industrial-real"]);
  assert.strictEqual(run.status, "passed");
  const checked = dispatch(["check-run", "--run-root", run.run_root]);
  assert.strictEqual(checked.status, "passed");
  assert.match(checked.reason, /native then complete 3D capture matrix passed/);
  assert.strictEqual(checked.capture_count, 12);
  const loaded = captureSet(run.run_root);
  assert.strictEqual(loaded.captures.length, 12);
  for (const capture of loaded.captures) { assert.strictEqual(capture.canonical.profile, "industrial-kinematics@1"); assert.deepStrictEqual(Object.keys(capture.canonical.industrial).sort(), ["anchor", "attachment", "joint", "socket"]); assert.strictEqual(JSON.stringify(capture.canonical).includes("verdict"), false); }
  assert.strictEqual(fs.existsSync(path.join(run.run_root, "attempt-1/.browser-runtime")), false);
});

test("production CLI run uses the async detached supervisor and leaves no process group", (t) => { const raw = fs.mkdtempSync(path.join(os.tmpdir(), "atlas-3d-cli-real-")), root = fs.realpathSync(raw); t.after(() => fs.rmSync(raw, { recursive: true, force: true })); const config = runtime(root), runs = path.join(root, "runs"); fs.mkdirSync(runs); const cli = path.resolve(__dirname, "../../bin/atlas-3d-harness.cjs"), invoke = (args) => { const result = spawnSync(process.execPath, [cli, ...args], { encoding: "utf8", maxBuffer: 4 * 1024 * 1024 }); if (result.status !== 0) throw new Error(result.stderr); return JSON.parse(result.stdout); }; const run = invoke(["run", "--scenario", scenario, "--runtime-config", config, "--artifact-root", runs, "--run-id", "supervised-real"]); assert.strictEqual(run.status, "passed"); assert.deepStrictEqual({ detached: run.supervisor.detached, shell: run.supervisor.shell, inner: run.supervisor.inner_deadline_ms, outer: run.supervisor.outer_deadline_ms, residual: run.supervisor.residual }, { detached: true, shell: false, inner: 875000, outer: 900000, residual: false }); assert.throws(() => process.kill(-run.supervisor.pgid, 0), /ESRCH/); const checked = invoke(["check-run", "--run-root", run.run_root]); assert.strictEqual(checked.status, "passed"); assert.strictEqual(checked.capture_count, 12); });
