"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); const test = require("node:test");
const { dispatch } = require("../../src/cli/main.cjs"); const { validate } = require("../../src/protocol/schema.cjs");
const scenarioFile = path.resolve(__dirname, "../../examples/basic-three/scenario.json"); const scenario = JSON.parse(fs.readFileSync(scenarioFile));
test("validate is strict, declarative, and bounded", () => { assert.strictEqual(dispatch(["validate", "--scenario", scenarioFile]).status, "valid"); for (const key of ["argv", "url", "path", "env", "executable", "channel", "proxy"]) assert.throws(() => validate("scenario.schema.json", { ...scenario, [key]: "injected" }), /additional properties/i); const huge = structuredClone(scenario); huge.viewports[0] = { width: 4096, height: 4096, device_scale_factor: 2 }; assert.throws(() => validate("scenario.schema.json", huge), /pixel cap/); });
test("runtime config rejects unknown execution selectors", () => { const runtime = { schema_version: 1, trust_profile: "reviewed-local@1", project_root: "/tmp/project", origin: "http://127.0.0.1:41733", host_profile: "current-mac-arm64@1", attempts: 1 }; assert.doesNotThrow(() => validate("runtime-config.schema.json", runtime)); for (const key of ["argv", "env", "executablePath", "channel", "proxy"]) assert.throws(() => validate("runtime-config.schema.json", { ...runtime, [key]: "bad" }), /additional properties/i); });
test("capture evidence accepts binding id and rejects token-shaped persistence", () => { const schema = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../../contracts/capture.schema.json"))); assert(schema.properties.captureBindingId); assert.strictEqual(Object.hasOwn(schema.properties, "captureToken"), false); });
test("compare entry shape rejects unsupported purpose and invalid roots cannot become pass", () => { assert.throws(() => dispatch(["compare", "--left", "/a", "--right", "/b", "--purpose", "pixel-regression"]), /UNSUPPORTED/); assert.strictEqual(dispatch(["compare", "--left", "/a", "--right", "/b", "--purpose", "semantic-state"]).status, "not_comparable"); });
test("invalid run input fails before derived inputs, server, or browser", (t) => { const os = require("os"), root = fs.realpathSync(fs.mkdtempSync(path.join(os.tmpdir(), "atlas-3d-zero-"))); t.after(() => fs.rmSync(root, { recursive: true, force: true })); const invalid = { ...scenario, argv: ["bad"] }, bad = path.join(root, "bad.json"), runtime = path.join(root, "runtime.json"), runs = path.join(root, "runs"); fs.writeFileSync(bad, JSON.stringify(invalid)); fs.writeFileSync(runtime, JSON.stringify({ schema_version: 1, trust_profile: "reviewed-local@1", project_root: path.dirname(scenarioFile), origin: "http://127.0.0.1:41733", host_profile: "current-mac-arm64@1", attempts: 1 })); fs.mkdirSync(runs); assert.throws(() => dispatch(["run", "--scenario", bad, "--runtime-config", runtime, "--artifact-root", runs, "--run-id", "zero"]), /additional properties/i); assert.deepStrictEqual(fs.readdirSync(runs), []); });
