"use strict";
const assert = require("assert"); const fs = require("fs"); const path = require("path"); const test = require("node:test");
const { LIMITS, boundedCounter, enforceLimitValue } = require("../../src/protocol/limits.cjs"); const { validate } = require("../../src/protocol/schema.cjs"); const { frozenResourceDigests, startServer } = require("../../src/launcher/server.cjs");
const scenario = JSON.parse(fs.readFileSync(path.resolve(__dirname, "../../examples/basic-three/scenario.json")));
const runtime = { schema_version: 1, trust_profile: "reviewed-local@1", project_root: path.resolve(__dirname, "../../examples/basic-three"), origin: "http://127.0.0.1:41733", host_profile: "current-mac-arm64@1", attempts: 1 };
test("every frozen count and byte limit accepts exact and rejects one-over without allocation", () => { for (const [name, limit] of Object.entries(LIMITS)) { assert.strictEqual(enforceLimitValue(limit, limit, `${name}_LIMIT`), limit, name); assert.throws(() => enforceLimitValue(limit + 1, limit, `${name}_LIMIT`), new RegExp(`${name}_LIMIT`), name); } });
test("streaming counters accept exact cumulative count and reject the next event", () => { for (const name of ["max_capture_count", "max_network_events", "max_console_events", "max_lifecycle_events", "max_evidence_refs", "max_temp_files"]) { const counter = boundedCounter(LIMITS[name], `${name}_LIMIT`); counter.add(LIMITS[name] - 1); assert.strictEqual(counter.add(), LIMITS[name]); assert.throws(() => counter.add(), new RegExp(`${name}_LIMIT`)); } });
test("scenario and runtime inputs cannot inject, disable, or relax limits", () => { assert.throws(() => validate("scenario.schema.json", { ...scenario, limits: {} }), /additional properties/i); assert.throws(() => validate("runtime-config.schema.json", { ...runtime, limits: { max_pixels: Number.MAX_SAFE_INTEGER } }), /additional properties/i); const oversized = structuredClone(scenario); oversized.viewports[0] = { width: 4096, height: 4096, device_scale_factor: 2 }; assert.throws(() => validate("scenario.schema.json", oversized), /pixel cap/); });
test("served response enforces Content-Length and body cap at exact and one-over", async () => { const allocation = Buffer.alloc(LIMITS.max_response_bytes + 1); const exact = await startServer({ expectedDigests: frozenResourceDigests(), overrides: { index: allocation.subarray(0, LIMITS.max_response_bytes) }, port: 41734 }); try { const response = await fetch(exact.origin + "/"); assert.strictEqual(Number(response.headers.get("content-length")), LIMITS.max_response_bytes); assert.strictEqual((await response.arrayBuffer()).byteLength, LIMITS.max_response_bytes); } finally { await exact.close(); } const over = await startServer({ expectedDigests: frozenResourceDigests(), overrides: { index: allocation }, port: 41734 }); try { const response = await fetch(over.origin + "/"); assert.strictEqual(response.status, 413); assert.strictEqual(Number(response.headers.get("content-length")), 0); } finally { await over.close(); } });
